% source_dir = '/Users/olgadalmonte/Dropbox/Universita Torino/Progetti/Social Touch and pupils/pupil/subset_processed';
source_dir = '/Users/Nick/Downloads/pupil 2/reprocessed_olga';
source_mats = shared_utils.io.findmat( source_dir, true );

pupil_outs = pupil_load_processed( source_mats );

%%

% panels = body part; arm shoulder hand

%%

line_plot_dir = '~/Desktop/pupil/plots/lines';
bar_plot_dir = '~/Desktop/pupil/plots/bars';

do_save = true;
task_type = pupil_task_type( 'wood-hand' );

%%  Plot lines for each subject and / or each subject, each trial

pupil_plot_subject_data_lines( pupil_outs ...
  , 'save', do_save ...
  , 'save_dir', line_plot_dir ...
  , 'plot_funcs', {'plot_each_trial_per_subject', 'plot_conditions_per_subject'} ...
  , 'prefix', '' ...
  , 'task_type', task_type ...
  , 'per_trial_number', true ...
);

%%  Plot lines across subjects

pupil_plot_subject_data_lines( pupil_outs ...
  , 'save', do_save ...
  , 'save_dir', line_plot_dir ...
  , 'mask_func', @rowmask ...
  , 'plot_funcs', {'plot_conditions_across_subjects'} ...
  , 'prefix', '' ...
  , 'task_type', task_type ...
  , 'per_trial_number', false ...
);

%%  Plot bars

pupil_plot_bar_summary( pupil_outs ...
  , 'save', do_save ...
  , 'save_dir', bar_plot_dir ...
  , 'mask_func', @(l) rowmask(l) ...
  , 'normalize', true ...
  , 'base_t', [0, 2e3] ...
  , 'target_t', [2e3, 8e3] ...
  , 'prefix', '2-to-8' ...
  , 'task_type', task_type ...
  , 'per_trial_number', false ...  
  , 'per_panel_labels', true ...
);
