source_dir = '~/Desktop/subset';
source_mats = shared_utils.io.findmat( source_dir, true );

pupil_outs = pupil_load_processed( source_mats );

%%

line_plot_dir = '~/Desktop/plots/lines';
bar_plot_dir = '~/Desktop/plots/bars';

do_save = true;

%%  Plot lines for each subject and / or each subject, each trial

pupil_plot_subject_data_lines( pupil_outs ...
  , 'save', do_save ...
  , 'save_dir', line_plot_dir ...
  , 'plot_funcs', {'plot_conditions_per_subject', 'plot_each_trial_per_subject'} ...
  , 'prefix', '' ...
);

%%  Plot lines across subjects

pupil_plot_subject_data_lines( pupil_outs ...
  , 'save', do_save ...
  , 'save_dir', line_plot_dir ...
  , 'mask_func', @pupil_select_subject_and_block ...
  , 'plot_funcs', {'plot_conditions_across_subjects'} ...
  , 'prefix', '' ...
);

%%  Plot bars

pupil_plot_bar_summary( pupil_outs ...
  , 'save', do_save ...
  , 'save_dir', bar_plot_dir ...
  , 'mask_func', @pupil_select_subject_and_block ...
  , 'normalize', true ...
  , 'base_t', [0, 2e3] ...
  , 'target_t', [2e3, 8e3] ...
  , 'prefix', '2-to-8' ...
);
